config/routes.rb
Rails.application.routes.draw do
	
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  resources :categories do
  	resources :products  
  end

  resources :comments
  
  resources :users do
    collection do
      get :profile
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	
	has_many :products, dependent: :destroy

	accepts_nested_attributes_for :products
	
	has_many :images, as: :imagable, inverse_of: :imagable

    accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :product
  belongs_to :user

end

app/models/image.rb
class Image < ApplicationRecord

  belongs_to :imagable, polymorphic: true, inverse_of: :imagable
  mount_uploader :file, ImageUploader
  
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category

	has_many :comments

  	has_many :images, as: :imagable, inverse_of: :imagable

    accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments       

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @categories = Category.order('created_at DESC')
  end

  def show
    @category = Category.find(params[:id])
  end
  

  private

  def category_params
    params.require(:category).permit(:title, :body, images_attributes: [:id, :file, :_destroy])
  end
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
 
  before_filter :authenticate_user!, only: [:new]
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  
 
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end
 
  # GET /comments/1
  # GET /comments/1.json
  def show
  end
 
  # GET /comments/new
  def new
    @comment = current_user.comments.new
    
  end
 
  # GET /comments/1/edit
  def edit
  end
 
  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
 
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Комментарий успешно создан.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
 
  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Комментарий успешно обновлен.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
 
  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    redirect_to comments_path(@comments)
  end
 
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
    
  end

  def comment_params
    params.require(:comment).permit(:body, :product_id, :user_name, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
  def index
  	@products = Product.where({'favorit' => true})
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  def new
    @image = @product.images.new
    @image = @category.images.new
    @image = @user.images.new
  end

  def create
    @product.images.create(image_params)
    @category.images.create(image_params)
    @user.images.create(image_params)
  end


  private

  def image_params
    params.require(:image).permit(:file)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_category

  def index
    @product = Product.all
    @products = @category.products
    @q = Product.ransack(params[:q])
    @products = @q.result.order('created_at DESC')

  end

  def show
    @product = Product.find(params[:id])
    @comments = @product.comments.all
    @comment = @product.comments.build
  end
  
 
  private

    def set_category
      @category = Category.find(params[:category_id])
    end

    def product_params
      params.require(:product).permit(:price, :name, :pr_description, :favorit, images_attributes: [:id, :file, :_destroy])
    end
end

 

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
    @user = current_user
  end

  def update
    current_user.update(user_params)
    redirect_to profile_users_path
  end

  def create
    User.create(user_params)
    redirect_to profile_users_path
  end


  private

  def user_params
    params.require(:user).permit(:first_name,
    :last_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<div class="container padding">
  <h1 class="text-center padding_top">Группы</h1>
  <div class="group_box padding">

    <% @categories.each do |category| %>

    <div class="left_side">
      <div class="first_foto oneImg">
        <% category.images.each do |image| %>
          <%= image_tag(image.file_url, class: 'photos ng-scope') %>
        <% end %>
      </div>
      <div class="other_foto">
        <% category.images.each do |image| %>
          <%= image_tag(image.file_url, class: 'photos ng-scope') %>
        <% end %>
      </div>
    </div>

    <div class="group_info">
      <h2><%= link_to category.title, category_path(category) %></h2>
      <p><%= category.body %></p>
    </div>
  </div> 
  <% end %>
</div>


 

app/views/categories/show.html.erb
<div class="container padding_top">
  <img class="circle oneImg"
    <% @category.images.each do |image|%>
      <%= image_tag(image.file_url) %>
    <% end %> 
  <h1 class="text-center">Категории</h1>
  <h2><%= @category.title %></h2>
  <p>
    <%= @category.body %>
    On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.
    On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.     
  </p>
  <button class="btn btn-lg" type="button"><%= link_to 'Продукты', category_products_path(@category) %>
  </button>
  <div class="shaped"></div>
    <div class="content">
      <h2 class="text-center">Описание чего-либо</h2>
        <p>
          On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.
          On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.
        </p>
   </div>
</div>

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br> 
  
    <%= current_user.full_name%>

  <form class="pure-form" id="comment-form">
    <div class="comment-form">
      <div class="left-side">
        <div class="row">
          <input type="text" required placeholder="<%= current_user.full_name%>" id="new_comment_name">
          <%= f.number_field :product_id, placeholder: "product id" %>
        </div>
        <div class="row">
          <%= f.text_area :body, placeholder: "enter comment text" %>
        </div>
      </div>
     <div class="right-side">
        <button type="submit" class="button-secondary">Send Comment</button>
     </div>
    </div>
  </form>

<% end %>

app/views/comments/edit.html.erb
<h1 class= "padding_top" >Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment, class: "button-secondary" %>
<%= link_to 'Back', comments_path, class: "button-secondary" %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class= "padding_top">Comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Product ID</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user.full_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.product_id %></td>
        <td><%= comment.product.name %></td>
        <td><%= link_to 'Show', comment %></td>

        <% if current_user.try(:admin?) %>

        <td><%= link_to 'Edit', comment%></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path, class: "button-secondary" %>

app/views/comments/new.html.erb
<h1 class= "padding_top">New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Все Комментарии', comments_path, class: "button-secondary" %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p class= "padding_top">
  <strong>Author:</strong>
  <%= @comment.user.full_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Product:</strong>
  <%= @comment.product_id %>
</p>

<% if current_user.try(:admin?) %>

<%= link_to 'Edit', edit_comment_path(@comment), class: "button-secondary" %> |
<% end %>
<%= link_to 'Back', comments_path, class: "button-secondary" %>

app/views/home/index.html.erb
<div class="padding_top">
  <div class="carousel slide" data-ride="carousel" id="slides">

  <ul class="carousel-indicators">
    <li data-target="#slides" data-slide-to="0" class="active"></li>
    <li data-target="#slides" data-slide-to="1"></li>
    <li data-target="#slides" data-slide-to="2"></li>
  </ul>

  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="assets/1.jpg">
      <div class="carousel-caption">
        <h1 class="display-2">РЮКЗАКИ</h1>
        <h3>Что-то про рюкзаки</h3>
        <button type="button" class="btn btn-outline-light btn-lg">Посмотреть</button>
        <button type="button" class="btn btn-warning btn-lg">Кнопка</button>
      </div>
    </div>
    <div class="carousel-item">
      <img src="assets/2.jpg">
    </div>
    <div class="carousel-item">
       <img src="assets/3.jpg">
    </div>
  </div>    
</div>
</div>


<div class="container-fluid">
  <div class="row jumbotron">
    <div class="text_review col-xs-12 col-sm-12">
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio placeat consequatur tempore aut eaque, dignissimos sint temporibus accusantium explicabo ducimus doloremque totam excepturi quod, vel saepe ex aliquam hic! Voluptates?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt corporis nemo adipisci, repudiandae, doloremque ullam eius ea vitae officiis voluptatem, magnam temporibus dolorem unde dolorum! Deleniti fuga alias, explicabo suscipit.</p>
    </div>
    <div class="col-xs-12 col-sm-12 vol-md-3 col-lg-3 col-xl-2">
      

  </div>
</div>

<div class="container-fluid">
  <div class="row text-center alert">
    <div class="col-12">
      <h1 class="display-4">НАЗВАНИЕ</h1>
    </div>
    <hr>
    <div class="col-12">
      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus voluptas, provident nostrum at voluptates itaque ipsum? Culpa voluptate, minus cumque minima totam, officiis quam voluptas necessitatibus quibusdam aut, dolorum magnam. Ullam beatae ducimus tempore nostrum praesentium accusantium adipisci debitis voluptatibus impedit, similique maiores alias illo fugiat natus quaerat repellat totam, quasi voluptatem sit libero. Inventore nesciunt deleniti, iusto sit perferendis.</p>
    </div>
  </div>
</div>

<div class="container-fluid padding">
  <div class="row text-center padding">
    <div class="col-xs-12 col-sm-6 col-md-4">
      <i class="fas fa-code"></i>
        <h3>HTML5</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <i class="fas fa-bold"></i>
        <h3>Bootstrap</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <i class="fab fa-css3"></i>
        <h3>CSS3</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
    </div>
  </div>
  <hr class="my-4">
</div>

<figure>
  <div class="fixed-wrap">
    <div id="fixed">
      
    </div>
  </div>
</figure>

<div class="text-center">
  <button type="button" class="btn btn-success" id="gifsBtn" data-toggle="collapse" data-target="#gif">Открыть блок</button>
</div>
<div class="collapse gifs" id="gif">
  <div class="container-fluid paddind">
    <div class="row text-center">
      <div class="col-sm-6 col-md-3">
        <img src="assets/1.jpg" alt="">
      </div>
      <div class="col-sm-6 col-md-3">
        <img src="assets/2.jpg" alt="">
      </div>
      <div class="col-sm-6 col-md-3">
        <img src="assets/3.jpg" alt="">
      </div>
      <div class="col-sm-6 col-md-3">
        <img src="assets/4.jpg" alt="">
      </div>
    </div>

  </div> 
</div>

<h1 class="display-4 text-center" id="best_prod">Лучшие товары</h1>
<div class="container padding">
  <div class="prod_box padding">

    <% @products.each do |product| %>
    <div class="prod_info text-center">
      <div class="rotate">
        <div class="prod_img oneImg">
          <% product.images.each do |image| %>
            <%= image_tag(image.file_url, class: 'img-responsive img-rounded') %>
          <% end %>
        </div>
        
        <div class="text">
          <div class="pd">
            <h3 class="card-title"><%= product.name%></h4>
            <p class="description"><%= product.pr_description %></p>
            <p>Цена: <%= product.price %></p>

            <button type="button" class="btn btn-success" >Открыть блок</button>
          </div>
        </div> 
      </div> 
    </div>
    <% end %>
  </div>  
</div>
<details>Покажи, что у тебя есть!</details>
<br>
<dl>
  <dt>GIF</dt>
  <dd>Формат графических файлов, широко применяемый при создании сайтов. 
   GIF использует 8-битовый цвет и эффективно сжимает сплошные цветные области, 
   при этом сохраняя детали изображения.</dd>
  <dt>JPEG</dt>
  <dd>Популярный формат графических файлов, широко применямый при создании 
  сайтов и хранения изображений. JPEG поддерживает 24-битовый цвет и сохраняет 
  яркость и оттенки цветов в фотографиях. Данный формат называют сжатием с потерями, 
  поскольку алгоритм JPEG выборочно отвергает данные. Метод сжатия может исказить 
  деталь в рисунке, особенно содержащий текст или изображение с четкими краями. 
  Формат JPEG не поддерживает прозрачность, когда вы сохраняете фотографию в формате 
  JPEG, прозрачные пиксели заполняются определенным цветом.</dd>
</dl>
 <div class="block1">Lorem ipsum dolor sit amet, consectetuer 
   adipiscing elit, sed diem nonummy nibh euismod tincidunt ut lacreet 
   dolore magna aliguam erat volutpat.</div>
  <div class="block2">Ut wisis enim ad minim veniam, quis nostrud 
   exerci tution ullamcorper suscipit lobortis nisl ut aliquip ex 
   ea commodo consequat.</div> 
<br>
<form action="handler.php">
  <fieldset>
   <legend>Работа со временем</legend>
     <input type="checkbox"> создание пунктуальности (никогда не 
      будете никуда опаздывать);<br>
     <input type="checkbox"> излечение от пунктуальности (никогда 
      никуда не будете торопиться);<br>
     <input type="checkbox"> изменение восприятия времени и часов.
      <p><input type="submit"></p>
  </fieldset>
 </form> 
<br>
<form name="test" method="post" action="input1.php">
  <p><b>Ваше имя:</b><br>
   <input type="text" size="40">
  </p>
  <p><b>Каким браузером в основном пользуетесь:</b><Br>
   <input type="radio" name="browser" value="ie"> Internet Explorer<Br>
   <input type="radio" name="browser" value="opera"> Opera<Br>
   <input type="radio" name="browser" value="firefox"> Firefox<Br>
  </p>
  <p>Комментарий<Br>
   <textarea name="comment" cols="40" rows="3"></textarea></p>
  <p><input type="submit" value="Отправить">
   <input type="reset" value="Очистить"></p>
</form>
<br>
<main>
  История о том, как возле столовой появились загадочные розовые 
  следы с шестью пальцами, и почему это случилось. 
</main>
<br>
<marquee behavior="alternate" direction="left" bgcolor="#ffcc00">
    Lorem ipsum dolor sit amet...
</marquee>

<br>

app/views/products/index.html.erb
<div class="container padding">
  <h1 class="text-center padding_top">Продукты Группы</h1>
  <div class="prod_case_box padding">

    <% @category.products.each do |product| %>
    <div class="prod_case_info">
      <h2><%= link_to product.name, category_product_path(@category, product)%></h2>
      <h3 class="card-title pricing-card-title">Цена: <%= product.price %></h3>
      <p class="description"><%= product.pr_description %></p>
    </div>

    <div class="prod_case_img oneImg">
      <% product.images.each do |image| %>
        <%= image_tag(image.file_url) %>
      <% end %>
    </div>
    <% end %>
  </div> 
</div>

app/views/products/show.html.erb
<div class="container padding_top">
  <div class="oneImg">
    <img class="circle"
    <% @product.images.each do |image|%>
      <%= image_tag(image.file_url) %>
    <% end %> 
  
    <h2 class="text-center padding_top"><%= @product.name %></h2>
    <h3 class="card-title pricing-card-title">Цена: <%= @product.price %></h3>
    <p>
      <%= @product.pr_description %>
      On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.
      On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.    
    </p>
  </div>
  
</div>
<div class="container padding">
    <div class="img_section1">
      <div class="prod_img1">
        <% @product.images.each do |image| %>
          <%= image_tag(image.file_url) %>
        <% end %>
      </div>
    </div>
 
  <!-- Button trigger modal -->

  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
    Описание
  </button>

  <!-- Modal -->
  <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p><%= @product.pr_description %></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>
<h3>Comments</h3>
<% @comments.each do |comment| %>
  <div>
    <strong><%= comment.user.full_name %></strong>
    <br>
    <strong><%= comment.product_id %></strong>
    <br>
    <p><%= comment.body %></p>
  </div>
<% end %>
<%= link_to 'СообщениЯ', comments_path(@comment) %> 

app/views/users/profile.html.erb
<div class=" text-center padding_top">     
  <h1>My Profile</h1>

  <%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <%= f.submit 'Save', class: 'btn btn-default' %>
  <% end %>
</div> 