config/routes.rb
Rails.application.routes.draw do
	
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  resources :categories do
  	resources :products  
  end

  resources :comments
  
  resources :users do
    collection do
      get :profile
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	
	has_many :products, dependent: :destroy

	accepts_nested_attributes_for :products
	
	has_many :images, as: :imagable, inverse_of: :imagable

    accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :product
  belongs_to :user

end

app/models/image.rb
class Image < ApplicationRecord

  belongs_to :imagable, polymorphic: true, inverse_of: :imagable
  mount_uploader :file, ImageUploader
  
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category

	has_many :comments

  	has_many :images, as: :imagable, inverse_of: :imagable

    accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments       

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @categories = Category.order('created_at DESC')
  end

  def show
    @category = Category.find(params[:id])
  end
  

  private

  def category_params
    params.require(:category).permit(:title, :body, images_attributes: [:id, :file, :_destroy])
  end
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
 
  before_filter :authenticate_user!, only: [:new]
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  
 
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end
 
  # GET /comments/1
  # GET /comments/1.json
  def show
  end
 
  # GET /comments/new
  def new
    @comment = current_user.comments.new
    
  end
 
  # GET /comments/1/edit
  def edit
  end
 
  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
 
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Комментарий успешно создан.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
 
  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Комментарий успешно обновлен.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
 
  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    redirect_to comments_path(@comments)
  end
 
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
    
  end

  def comment_params
    params.require(:comment).permit(:body, :product_id, :user_name, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
  def index
  	@products = Product.where({'favorit' => true})
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  
  def new
    @image = @product.images.new
    @image = @category.images.new
    @image = @user.images.new
  end

  def create
    @product.images.create(image_params)
    @category.images.create(image_params)
    @user.images.create(image_params)
  end


  private

  def image_params
    params.require(:image).permit(:file)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_category

  def index
    @product = Product.all
    @products = @category.products
    @q = Product.ransack(params[:q])
    @products = @q.result.order('created_at DESC')

  end

  def show
    @product = Product.find(params[:id])
    @comments = @product.comments.all
    @comment = @product.comments.build
  end
  
 
  private

    def set_category
      @category = Category.find(params[:category_id])
    end

    def product_params
      params.require(:product).permit(:price, :name, :pr_description, :favorit, images_attributes: [:id, :file, :_destroy])
    end
end

 

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def profile
    @user = current_user
  end

  def update
    current_user.update(user_params)
    redirect_to profile_users_path
  end

  def create
    User.create(user_params)
    redirect_to profile_users_path
  end


  private

  def user_params
    params.require(:user).permit(:first_name,
    :last_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_menu.html.erb
<img class="navbar-brand">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
    <span class="navbar-toggler-icon"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>

<div class="collapse navbar-collapse" id="navbarResponsive">
  <ul class="nav nav-pills navbar-nav ml-auto">
    <li class="nav-item dropdown active">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Главная</a>
      <div class="dropdown-menu">
        <%= link_to 'Главная', root_path, {:class=>"nav-link"}%>
        <div role="separator" class="dropdown-divider"></div>
        <a class="dropdown-item" href="#footer">Контакты</a>
      </div>  
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Каталоги</a>
        <ul class="dropdown-menu">
          <li class="">
            <%= link_to 'Каталоги', categories_path, {:class=>"nav-link"} %>
          </li>
          <li class=""><a href=""><ion-icon name="beer"></ion-icon></a></li>
          <li class=""><a href="">Действие</a></li>
          <li class="divider" ></li>
          <li class="dropdown-header">Заголовок</li>
          <li class=""><a href="">Действие</a></li>
        </ul>
    </li>
  </ul> 
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li><%= current_user.email %></li>
      <li>
        <%= link_to current_user.full_name, profile_users_path %>  
      </li>
      <li>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to 'Login', new_user_session_path %>
      </li>
      <li>
        <%= link_to 'Registration', new_user_registration_path %>
      </li>
    <% end %>
  </ul>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %>Рюкзаки</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,700" rel="stylesheet">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md bg-light fixed-top" role="navigation" id="navbar-example2">
        <div class="container-fluid">
          <%= render partial: 'layouts/menu' %>
        </div>
      <nav>
    </header>

    <%= yield %>
    <footer class="container-fluid" id="footer">
      <div class="container-fluid">
        <div class="row padding text-center">
          <div class="col-12">
            <h2>Наши контакты</h2>
          </div>
          <div class="col-12 social padding">
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-youtube"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-google"></i></a>
          </div>
        </div>
      </div>
    </footer>  
  </body>
</html>